apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopilot-hub-annonymous
rules:
  - apiGroups:
      - subresource.kopilot.smartx.com
    resources:
      - clusters/agent
      - clusters/connect
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopilot-hub-annonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopilot-hub-annonymous
subjects:
  - kind: User
    name: system:anonymous
