apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopilot-hub
  namespace: kopilot-system
spec:
  replicas: 2
  selector:
    matchLabels:
      name: kopilot-hub
  template:
    metadata:
      labels:
        name: kopilot-hub
    spec:
      serviceAccountName: kopilot-hub
      containers:
        - name: kopilot-hub
          image: kopilot-hub
          env:
            - name: PUBLIC_ADDR
              valueFrom:
                configMapKeyRef:
                  name: kopilot-hub
                  key: public_addr
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8443
            - containerPort: 6443
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-subresource-server/cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: kopilot-hub-cert
            defaultMode: 420
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kopilot-hub
  namespace: kopilot-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopilot-hub-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: kopilot-hub
    namespace: kopilot-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopilot-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopilot-hub
subjects:
  - kind: ServiceAccount
    name: kopilot-hub
    namespace: kopilot-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kopilot-hub-endpoints
  namespace: kopilot-system
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    resourceNames:
      - kopilot-hub
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kopilot-hub-endpoints
  namespace: kopilot-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kopilot-hub-endpoints
subjects:
  - kind: ServiceAccount
    name: kopilot-hub
    namespace: kopilot-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kopilot-hub-cert
  namespace: kopilot-system
spec:
  issuerRef:
    kind: Issuer
    name: kopilot-cert-issuer
  dnsNames:
    - kopilot-hub.kopilot-system.svc
    - kopilot-hub.kopilot-system.svc.cluster.local
  secretName: kopilot-hub-cert
---
apiVersion: v1
kind: Service
metadata:
  name: kopilot-hub
  namespace: kopilot-system
spec:
  selector:
    name: kopilot-hub
  ports:
    - name: api
      port: 443
      targetPort: 8443
    - name: peer
      port: 6443
      targetPort: 6443
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.subresource.kopilot.smartx.com
  annotations:
    cert-manager.io/inject-ca-from: kopilot-system/kopilot-hub-cert
spec:
  group: subresource.kopilot.smartx.com
  groupPriorityMinimum: 2000
  version: v1alpha1
  versionPriority: 10
  service:
    name: kopilot-hub
    namespace: kopilot-system
