apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: kopilot-system/kopilot-hub-webhook-server-cert
webhooks:
  - name: mutate.cluster.v1alpha1.kopilot.smartx.com
    clientConfig:
      service:
        name: kopilot-hub-webhook
        namespace: kopilot-system
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: kopilot-system/kopilot-hub-webhook-server-cert
webhooks:
  - name: validate.cluster.v1alpha1.kopilot.smartx.com
    clientConfig:
      service:
        name: kopilot-hub-webhook
        namespace: kopilot-system
