apiVersion: v1
kind: Namespace
metadata:
  name: kopilot-system
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kopilot-cert-issuer
  namespace: kopilot-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kopilot-hub-peer-cert
  namespace: kopilot-system
spec:
  dnsNames:
    - kopilot-hub.kopilot-system.svc
    - kopilot-hub.kopilot-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kopilot-cert-issuer
  secretName: kopilot-hub-peer-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopilot-hub
  namespace: kopilot-system
spec:
  replicas: 2
  selector:
    matchLabels:
      name: kopilot-hub
  template:
    metadata:
      labels:
        name: kopilot-hub
    spec:
      serviceAccountName: kopilot-hub
      containers:
        - name: kopilot-hub
          image: kopilot-hub
          env:
            - name: PUBLIC_ADDR
              valueFrom:
                configMapKeyRef:
                  name: kopilot-hub
                  key: public_addr
          ports:
            - name: webhook
              containerPort: 9443
            - name: peer
              containerPort: 6443
          volumeMounts:
            - name: webhook-server-cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            - name: peer-cert
              mountPath: /tmp/kopilot-hub/peer-certs
              readOnly: true
        - name: kube-rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:v0.10.0
          ports:
            - name: https
              containerPort: 8443
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --ignore-paths=/kopilot-agent.yaml,/connect
            - --logtostderr=true
      volumes:
        - name: webhook-server-cert
          secret:
            secretName: kopilot-hub-webhook-server-cert
            defaultMode: 420
        - name: peer-cert
          secret:
            secretName: kopilot-hub-peer-cert
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: kopilot-hub
  namespace: kopilot-system
spec:
  type: NodePort
  selector:
    name: kopilot-hub
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: peer
      port: 6443
      targetPort: peer
