apiVersion: v1
kind: Namespace
metadata:
  name: kopilot-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopilot-agent
  namespace: kopilot-system
spec:
  replicas: 2
  selector:
    matchLabels:
      name: kopilot-agent
  template:
    metadata:
      labels:
        name: kopilot-agent
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: kopilot-agent
          image: "{{ .imageName }}"
          args:
            - -connect
            - "{{ .connectURL }}"
          volumeMounts:
            - name: kubernetes-pki
              mountPath: /etc/kubernetes/pki
              readOnly: true
      volumes:
        - name: kubernetes-pki
          hostPath:
            path: "{{ .k8sPKIDir }}"
