name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - run: make test

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - run: >
          docker run -v $PWD:/workspace -w /workspace golang:1.16.6-alpine3.14@sha256:982d77b170e0a8018ff0013fec14c825d84d1f310e7075935bdc7e97c1730b7d
          /bin/sh -c "apk add gcc musl-dev && go test -p 1 ./..."
