name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - run: make test

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - run: docker run -v $PWD:/workspace -w /workspace golang:1.16.4@sha256:5f6481e8bc6f0749586b45b3daa59e7f4937a5bf5a1c2b2a7fb16bc4e9cf4850 go test -p 1 ./...
